[package]
name = "MoonOS"
version = "0.1.0"
edition = "2024"

[lib]
name = "kernel"
path = "kernel/lib.rs"
crate-type = ["staticlib"]

[dependencies]
limine = "0.5.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"