[package]
name = "MoonKernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kernel"
path = "kernel/main.rs"

[dependencies]
limine = "0.5.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
